Fix gen_python_files usage for black>=21.8b0
akaihola/darker pull request #189
Opened 2021-09-03 08:43 UTC by flying-sheep

This should fix the tests and be backwards compatible

2021-09-03 18:57 UTC, akaihola commented
@flying-sheep oops, I already had a fix for this in #183. The difference is that my solution looks at `black.__version__` and you're inspecting the actual signature of the function. Is this just a matter of taste or do you see pros and cons in each approach?

2021-09-03 18:58 UTC, akaihola commented on src/darker/black_diff.py
> +    # those two exist and are required in black>=21.8b0
They were actually introduced in `21.7b1.dev9`.

2021-09-03 19:03 UTC, akaihola commented on src/darker/black_diff.py
> +    kwa = dict(verbose=False, quiet=False) if "verbose" in sig.parameters else {}
Just a stylistic thing, I'd use the more commonly seen name `kwargs` for the extra keyword arguments.
```suggestion
    kwargs = dict(verbose=False, quiet=False) if "verbose" in sig.parameters else {}
```

2021-09-03 19:04 UTC, akaihola commented on src/darker/black_diff.py
> +            **kwa,
...here, too
```suggestion
            **kwargs,
```

2021-09-03 19:07 UTC, akaihola commented
Could you add a change log entry similar to [the one in the alternative pull request](https://github.com/akaihola/darker/pull/183/files#diff-ff3c479edefad986d2fe6fe7ead575a46b086e3bbcf0ccc86d85efc4a4c63c79R15)?

2021-09-03 19:09 UTC, akaihola requested changes
You can see a couple of comments in the review. I'm starting to think I like the `inspect` approach better than looking at the Black version.

2021-09-03 22:45 UTC, flying-sheep commented
> Is this just a matter of taste or do you see pros and cons in each approach?

I think the approach here is simpler in two ways:

1. it uses less code
2. it checks directly for the difference that has to be handled as opposed to taking an indirect route over the version

but ultimately it’s a matter of taste as both solutions are likely to be robust.

2021-09-04 06:15 UTC, akaihola approved these changes
Thanks @flying-sheep for the improved solution!

2021-09-04 06:15 UTC, merged