Add info for vim in readme.
akaihola/darker pull request #61
Opened 2020-08-26 00:10 UTC by Carreau

2020-08-27 17:22 UTC, akaihola requested changes
It's great to have detailed instructions for different IDE/editor environments! Thanks!

2020-08-27 17:22 UTC, akaihola commented on README.rst
> +Unlike black and many other formatter darker needs access to the git history,
```suggestion
Unlike black and many other formatters ``darker`` needs access to the Git history,
```

...just to unify spelling across the document.

2020-08-27 17:22 UTC, akaihola commented on README.rst
> +`.vimrc`:
```suggestion
``.vimrc``:
```

Double backticks required in RestructuredText to get monospace.

2020-08-27 17:22 UTC, akaihola commented on README.rst
> +You can though ask vim to run doarker on file save with the following in your
```suggestion
You can though ask vim to run ``darker`` on file save with the following in your
```
typo

2020-08-27 17:22 UTC, akaihola commented on README.rst
> +  - `%` for current file name.
The formatting was a bit off, this renders better in RestructuredText:

```suggestion
.. code-block:: vim

   autocmd BufWritePost *.py silent :!darker %

- ``BufWritePost`` to run darker *once the file has been saved*,
- ``silent`` to not ask for confirmation each time,
- ``:!`` to run an external command,
- ``%`` for current file name.
```

2020-08-28 00:52 UTC, Carreau commented
Sorry, my brain was in markdown mode when I wrote this.

2020-08-28 05:00 UTC, akaihola approved these changes

2020-08-28 05:02 UTC, akaihola commented
The build is failing due to the Black 20.8 update. Let's merge #58 first and rebase this one then.

2020-09-02 18:21 UTC, akaihola commented
> The build is failing due to the Black 20.8 update. Let's merge #58 first and rebase this one then.

I did the rebase and had to open a new pull request #70 since the branch is now in my repository instead of @Carreau's.

2020-09-02 18:21 UTC, closed without merging